// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// redisCommand
SEXP redisCommand(SEXP Rc, std::string cmd, List args);
RcppExport SEXP Rhiredis_redisCommand(SEXP RcSEXP, SEXP cmdSEXP, SEXP argsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP Rc = Rcpp::as<SEXP >(RcSEXP);
        std::string cmd = Rcpp::as<std::string >(cmdSEXP);
        List args = Rcpp::as<List >(argsSEXP);
        SEXP __result = redisCommand(Rc, cmd, args);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// redisConnect
SEXP redisConnect(std::string host = "localhost", int port = 6379);
RcppExport SEXP Rhiredis_redisConnect(SEXP hostSEXP, SEXP portSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string host = Rcpp::as<std::string >(hostSEXP);
        int port = Rcpp::as<int >(portSEXP);
        SEXP __result = redisConnect(host, port);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
