# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title General Redis Interface Function
#'
#'@description Perform any Redis command
#'
#'@export
redisCommand <- function(Rc, cmd, args) {
    .Call('Rhiredis_redisCommand', PACKAGE = 'Rhiredis', Rc, cmd, args)
}

#'@export
redisConnect <- function(host = "localhost", port = 6379L) {
    .Call('Rhiredis_redisConnect', PACKAGE = 'Rhiredis', host, port)
}

